<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>¿Te atreves al amor?</title>

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Pacifico&family=Poppins:wght@300;500&display=swap');

        body {
            font-family: 'Poppins', sans-serif;
            text-align: center;
            background-color: #ffe6e6; /* Fondo suave */
            color: #1e1e1e;
            margin: 0;
            padding: 0;
            height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            overflow: hidden;
            position: relative;
        }

        h1 {
            font-family: 'Pacifico', cursive;
            color: #ff1744; /* Color rojo del texto */
            text-shadow: 0px 4px 10px rgba(255, 20, 60, 0.7);
            font-size: 3.5vw; /* Tamaño de texto reducido */
            margin-bottom: 20px;
        }

        button {
            padding: 10px 20px;
            font-size: 2vw;
            margin: 20px;
            cursor: pointer;
            border: none;
            border-radius: 15px;
            background-color: #ff1744; /* Botón rojo */
            color: #fff; /* Texto en blanco */
            transition: all 0.3s ease-in-out;
            box-shadow: 0 5px 15px rgba(255, 20, 60, 0.7);
            font-family: 'Pacifico', cursive;
            text-transform: uppercase;
        }

        button:hover {
            background-color: #e91e63; /* Color al pasar el mouse */
            transform: scale(1.1);
        }

        #mensaje {
            font-size: 2vw; /* Tamaño de texto reducido */
            margin-top: 30px;
            display: none;
            color: #ff1744; /* Color del mensaje */
            text-shadow: 0px 4px 10px rgba(255, 20, 60, 0.7);
            line-height: 1.4;
            padding: 15px;
            background: rgba(255, 255, 255, 0.9); /* Fondo blanco para el mensaje */
            border-radius: 15px;
            max-width: 600px;
            margin-left: auto;
            margin-right: auto;
        }

        .corazon {
            color: red;
            font-size: 3vw; /* Tamaño de corazón reducido */
            display: inline-block;
            margin: 10px;
            animation: latir 1.2s infinite;
        }

        @keyframes latir {
            0% { transform: scale(1); }
            50% { transform: scale(1.2); }
            100% { transform: scale(1); }
        }

        #big-heart {
            display: none;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            font-size: 20vw; /* Tamaño de corazón grande reducido */
            color: red;
            animation: explotar 2s ease-in-out forwards;
        }

        @keyframes explotar {
            0% { transform: translate(-50%, -50%) scale(0.5); }
            50% { transform: translate(-50%, -50%) scale(1.5); }
            100% { transform: translate(-50%, -50%) scale(0); opacity: 0; }
        }

        .background-hearts {
            position: absolute;
            width: 100%;
            height: 100%;
            top: 0;
            left: 0;
            pointer-events: none;
            z-index: -1;
            overflow: hidden;
        }

        .background-heart {
            position: absolute;
            width: 20px;
            height: 20px;
            background-color: red;
            clip-path: polygon(50% 0%, 100% 38%, 80% 100%, 50% 78%, 20% 100%, 0% 38%);
            animation: float 15s ease-in-out infinite;
            opacity: 0.8;
        }

        @keyframes float {
            0% { transform: translateY(100vh) scale(0.8); opacity: 0.8; }
            100% { transform: translateY(-10vh) scale(1.2); opacity: 0; }
        }

        /* Ajustes responsivos */
        @media (max-width: 480px) {
            h1 {
                font-size: 7vw; /* Ajuste para móviles */
            }
            button {
                padding: 8px 16px;
                font-size: 5vw;
                width: 80px;
            }
            #mensaje {
                font-size: 4vw; /* Ajuste para móviles */
            }
            #big-heart {
                font-size: 45vw; /* Ajuste para móviles */
            }
            .corazon {
                font-size: 5vw; /* Ajuste para móviles */
            }
        }
    </style>
</head>
<body>
    <h1>¿Te gustaría arriesgarte a construir algo especial?</h1>
    <button id="si">Sí</button>
    <button id="no">No</button>

    <div id="mensaje">
        <p>En la sombra de la duda,<br>
        mi corazón se atreve a soñar,<br>
        te quiero con cada latido,<br>
        aunque el miedo me quiera parar.</p>
        <p>Tus ojos son faros en la niebla,<br>
        y en el riesgo quiero navegar,<br>
        con amor como brújula,<br>
        juntos, lo intentaremos a pesar.</p>
        <span class="corazon">&#10084;</span><span class="corazon">&#10084;</span><span class="corazon">&#10084;</span>
    </div>

    <div class="background-hearts"></div>
    <div id="big-heart">&#10084;</div>

    <!-- Audio de fondo -->
    <audio id="romantic-song" loop autoplay>
        <source src="Josean Log - Chachachá (Lyric Video).mp3" type="audio/mp3">
        Tu navegador no soporta audio.
    </audio>

    <script>
        const noButton = document.getElementById("no");
        const siButton = document.getElementById("si");
        const mensaje = document.getElementById("mensaje");
        const backgroundHearts = document.querySelector('.background-hearts');
        const bigHeart = document.getElementById("big-heart");
        const body = document.body;

        let noClickCount = 0;

        function createHeart() {
            const heart = document.createElement('div');
            heart.classList.add('background-heart');
            heart.style.left = `${Math.random() * 100}vw`;
            heart.style.animationDuration = `${Math.random() * 10 + 5}s`;
            backgroundHearts.appendChild(heart);
        }

        for (let i = 0; i < 50; i++) {
            createHeart();
        }

        noButton.addEventListener("click", function(event) {
            event.preventDefault();
            noClickCount++;
            if (noClickCount >= 5) {
                alert("Tal vez algún día cambies de opinión.");
                noClickCount = 0;
            }
        });

        siButton.addEventListener("click", function() {
            mensaje.style.display = "block";
            bigHeart.style.display = "block";
            noButton.style.display = "none"; // Ocultar el botón "No"

            for (let i = 0; i < 50; i++) {
                createHeart();
            }
        });
    </script>
</body>
</html>
